jg_form_homepage:
    path:     /
    defaults: { _controller: JGFormBundle:Default:index }


jg_form_valid:
    path:     /valid
    defaults: { _controller: JGFormBundle:Default:valid }


jg_form_edit:
     path:     /edit/{id}
     defaults: { _controller: JGFormBundle:Default:edit }


jg_form_delete:
     path:     /delete/{id}
     defaults: { _controller: JGFormBundle:Default:delete }



